name: Terraform
on: [push]
env:
    AWS_ACCESS_KEY_ID: ${{secrets.TERRA_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.TERRA_SECRET}}
jobs:
    s3:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: hashicorp/setup-terraform@v2
            with:
               terraform_version: 1.1.9
          - name: Initialization
            run: |
                 eval `ssh-agent -s`
                 ssh-add - <<< '${{ secrets.TERRA_PRIVATE }}'
                 terraform init
          - name: Validate
            run: terraform validate
          - name: Plan
            run: terraform plan
          - name: Apply
            run: terraform apply -auto-approve